image: alpine/3.21
packages:
  - stack
  - xz
  - build-base
  - gmp-dev
tasks:
  - build: |
      cd lua-bigint/tests
      stack build
  - tests: |
      cd lua-bigint/tests
      stack run specs
triggers:
  - action: email
    condition: always
    to: builds@rootmos.io
