image: alpine/3.21
packages:
  - stack
  - xz
  - build-base
  - gmp-dev
  - lua
tasks:
  - specs-accept-cabal-file: |
      cd lua-bigint/tests
      touch lua-bigint.cabal
  - specs-build: |
      cd lua-bigint
      make -C tests build
  - deps: |
      cd lua-bigint
      make deps
  - tests: |
      cd lua-bigint
      make tests
triggers:
  - action: email
    condition: always
    to: builds@rootmos.io
