image: alpine/3.21
packages:
  - stack
  - xz
  - build-base
  - gmp-dev
  - coreutils
environment:
  QUICKCHECK_VERBOSE: 1
  QUICKCHECK_MAX_SUCCESS: 1000
  QUICKCHECK_SIZE: 200
  LUA_BITS: 32
tasks:
  - specs-accept-cabal-file: |
      cd lua-bigint/tests
      touch lua-bigint.cabal
  - specs-build: |
      cd lua-bigint
      make -C tests build
  - deps: |
      cd lua-bigint
      make deps
  - tests: |
      cd lua-bigint
      make tests
triggers:
  - action: email
    condition: always
    to: builds@rootmos.io
