image: alpine/3.21
packages:
  - stack
  - xz
  - build-base
  - gmp-dev
tasks:
  - accept-cabal-file: |
      cd lua-bigint/tests
      touch lua-bigint.cabal
  - build: |
      cd lua-bigint
      make -C tests build
  - tests: |
      cd lua-bigint
      make -C tests run
triggers:
  - action: email
    condition: always
    to: builds@rootmos.io
