#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)
ROOT=${ROOT-$SCRIPT_DIR}
TOOLS=${TOOLS-$SCRIPT_DIR/tools}
SRC=${SRC-$SCRIPT_DIR/src}

OUTPUT_DIR=${1-$ROOT/dist}

mkdir -p "$OUTPUT_DIR"

env ROOT="$ROOT" "$TOOLS/build-info" -l -o "$SRC/build-info.lua"

OPTs=()

if env --chdir="$SRC" "${LUA-lua}" -l "B=build-info" -e "os.exit(B.version_prerelease and 0 or 1)"; then
    OPTs+=("--with-line-numbers")
fi

env --chdir="$SRC" "$TOOLS/bundle" "${OPTs[@]}" \
    -o "$OUTPUT_DIR/bignat.lua" "bignat.lua" \
    "arbbase.lua" \
    "ascii.lua" \
    "bits.lua" \
    "build-info.lua" \
    "internal.lua" \
    "polynomial.lua"

env --chdir="$SRC" "$TOOLS/bundle" "${OPTs[@]}" \
    -o "$OUTPUT_DIR/bigint.lua" "bigint.lua" \
    "arbbase.lua" \
    "ascii.lua" \
    "bignat.lua" \
    "bits.lua" \
    "build-info.lua" \
    "internal.lua" \
    "polynomial.lua"
