#!/bin/bash
# include
# https://git.sr.ht/~rootmos/scripts f9be0871a52d5e241c11b8f4f09e9a0dc4b51ab2 (dirty)
# 2025-04-17T19:17:10+02:00 SHA-256:5ba75751d3b08ec107418c906420f197de887430cbf7eaae0c300117b30b0608
# sed '2,5d' | sha256sum

set -o nounset -o pipefail -o errexit

INPUT=$1
OUTPUT=${2-/dev/stdout}

BASE_DIR=$(dirname "$INPUT")

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

awk '{
if(/^@include\s+"[^"]*"/) {
    rc = system(sprintf("cat %s/%s", "'"$BASE_DIR"'", $2))
    if(rc != 0) exit(rc)
} else {
    print($0)
} }' "$INPUT" > "$TMP"
cp "$TMP" "$OUTPUT"
#!/bin/bash
# include
# https://git.sr.ht/~rootmos/scripts 453d141f24be8dd830ebd480283ed41be413b29f
# 2025-04-17T19:18:38+02:00 SHA-256:5ba75751d3b08ec107418c906420f197de887430cbf7eaae0c300117b30b0608
# sed '2,5d' | sha256sum

set -o nounset -o pipefail -o errexit

INPUT=$1
OUTPUT=${2-/dev/stdout}

BASE_DIR=$(dirname "$INPUT")

TMP=$(mktemp)
trap 'rm -f $TMP' EXIT

awk '{
if(/^@include\s+"[^"]*"/) {
    rc = system(sprintf("cat %s/%s", "'"$BASE_DIR"'", $2))
    if(rc != 0) exit(rc)
} else {
    print($0)
} }' "$INPUT" > "$TMP"
cp "$TMP" "$OUTPUT"
