name: Release
on:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends lua5.4

      - name: Install release.py
        run: pipx install git+https://github.com/rootmos/release.py@releases/v0.2.1

      - name: Prepare release
        run: release -p
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create distribution files
        run: ./mk-dist
        env:
          LUA: lua5.4

      - name: Create release
        run: release -R dist/*.lua
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
