name: Run tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare Lua dependencies
      run: make -C deps

    - name: Prepare Haskell Tool Stack
      run: make -C tests prepare

    - name: Prepare Haskell dependencies
      run: make -C tests deps
